### PR TITLE
Update to the latest code

### PR DESCRIPTION
**Pull request by daleglass**
Hello!

In case you didn't know, High Fidelity changed track and took their repo offline. You were selected as the new upstream. It's a bit odd to be 82230 commits out of sync, so I figured I'd try to push the latest version there was before the repository was made private to you.

### CODE REVIEW

**Comment by yozlet** [comment]
WELL OKAY THEN

**Comment by yozlet** [comment]
Okay, I should probably expand this conversation.

I'm very happy for this repo to be brought up to date, but I'm also keen to know more about _why_.  What discussions have happened, who's been in them, and most importantly, what happens next. I saw the latest Hifi blog post, and that there have been layoffs. I don't need more than a couple of paragraphs of detail.

I've been almost entirely out of the Hifi loop since Philip paid me to spend a week doing the only OpenGL code I've ever written. (This was back when the company called itself Coffee And Power, and I had left Linden Lab a few months earlier.) I now have an entirely different job which consumes most of my time, so if this FOSS project is looking for an active maintainer, I'm afraid it ain't me.

That said, if there are small ways that I can help, I'm interested to hear about them. I hate to see an active community die for want of a home, unless it comes in and smears poo on the furniture and eats all my jam.

Oh, and you'll need to fix those conflicts before I can merge this PR, because as bad as poo-smearing is, I'd rather clean the couch than something called `SerialInterface.cpp`

**Comment by daleglass** [comment]
> I'm very happy for this repo to be brought up to date, but I'm also keen to know more about why. 

Really, it's not strictly necessary. When a repository is made private, github chooses a new upstream for the existing forks. In this case your was the chosen one. We've contacted github and it seems there's no way for us to get it to changed to something more sensible.

Why do this at all? Mostly for the sake of clarity, so that the difference between the original code and what we're doing can be seen in a clearer way. Our fork pre-dates the closing of the repo, so this obscures a bit the fact that there are some missing upstream changes still.

> What discussions have happened, who's been in them, and most importantly, what happens next. 

I came to HiFi in the last year, so I can't give you the history before that. Before I showed up, they were doing lots of events trying to attract people. This failed. In April, HiFi decided they'll change tracks, close all the domains they own and leave everything to the community, while they went to try to build a corporate meeting product of some sort from the codebase. It was invitation only and I didn't see it, but I've heard that the results were quite nice, but there's likely not that much of a market for it.

About a month ago they decided this wasn't working, shut down that effort as well as the remaining services (can't make new accounts anymore), laid off some people and are now doing some radical reorganization. Nobody knows what it involves.

There are 3 forks at this point:

* The Athena Project, an open source fork of the codebase. That's where I come from. We have a bunch of people working hard to get things running by replacing lost services and improving the code.
* Kitely. I don't know much about them. They're a closed fork.
* Tivoli Cloud. Started by Caitlyn and Maki. A currently very small, commercial, closed effort. I don't really know much about them either.

We're not looking for a maintainer or anything like that, but if you'd like to say hi, or to contribute anything, you'd be very welcome. We have a Discord at https://discord.gg/Pvx2vke


Regarding the merge, the easiest way would be for you to just discard your last commit, and force an update to the latest code found in the hifi-archive:master repo, as that contains the latest code the official repository contained before it went private.

**Comment by daleglass** [comment]
Oh, our main repository is located at https://github.com/kasenvr/project-athena/

This PR is sent from an archive of the unmodified hifi code.

**Comment by thoys** [comment]
Who's code reviewing this?

**Comment by sethalves** [comment]
@thoys don't be coy.  Let us know when you've finished.

**Comment by two-one-five** [comment]
Well we have to do a test suite on this. Who wants to test each set of commits after Thoys finishes reviewing? :3

**Comment by shadowcat-mst** [comment]
Quick point: if you create an org for athena it should be doable for @yozlet to transfer this repo to the org, assuming he wants to do that.

**Comment by yozlet** [comment]
@daleglass That was exactly what I needed to hear, thank you.

I'll have a go at discarding the last commit (or moving to its own branch) and pushing HEAD back one, then forcing a merge. I'm a long way from being a git maven, so if you have any specific commands I should do (or avoid) then let me know. (Out of interest, what's wrong with the last commit?)

**Comment by daleglass** [comment]
@yozlet You're welcome!

The last commit never made it into the official hifi repository. You can see this by:

    $ git clone https://github.com/yozlet/interface.git
    $ cd interface
    $ git remote add hifi https://github.com/hifi-archive/hifi.git              
    $ git fetch hifi  
    $ git merge-base origin/master hifi/master                                                                                        
    725d9f60a0047ef389de94e219247e8c4fd122ed

The last common commit between our repositories is your next-to-last one.

So, discard the last commit:

    $ git reset --hard HEAD~1

Merge:

    $ git merge hifi/master 

Force push:

    $ git push --force

**Comment by daleglass** [comment]
@shadowcat-mst 
> Quick point: if you create an org for athena it should be doable for @yozlet to transfer this repo to the org, assuming he wants to do that.

I have the hifi-archive organization already, it could be used for that. It's intended to be used as a static archive of where the official development left off: https://github.com/hifi-archive

**Comment by shadowcat-mst** [comment]
The awesome thing about that would be it would also let @yozlet do that first and then you can hit git with a shovel yourself ;)

**Comment by daleglass** [comment]
> The awesome thing about that would be it would also let @yozlet do that first and then you can hit git with a shovel yourself ;)

Sure, I could do that of course.

**Comment by yozlet** [comment]
# AND BEHOLD! IT IS, LIKE, DONE

@daleglass Thanks for [bringing the party to me](https://imgur.com/gallery/2e9Sg). I assume that it all looks good post-merge? Also, if we were to add a notice to the top of the README explaining the historical context, would that be OK or would it break anything?

@shadowcat-mst Transferring this repo to the Athena org is an interesting idea, but unless there are major arguments for moving it (which I'm very willing to consider) then I'd prefer to hang onto it for the moment.

**Comment by daleglass** [comment]
@yozlet You're welcome! Yes, everything looks good to me here.

I think extra commits might confuse things somewhat, but on the other hand, it's still going to be far less confusing than the situation there was before, and it's your repo after all.

Anyway, if you'd like to talk to us in a more comfortable manner for any reason, we mostly hang out at Discord. There are two:

The Project Athena discord: https://discord.gg/Pvx2vke
This is mainly dedicated to the development of our fork, though we do have open channels and welcome visitors.

The Federated Metaverse Users discord: https://discord.gg/uczNZQ
This was the big hangout during hifi's existence, and is more socially themed. It's generalized into covering anything metaverse related, including of course all the forks of the original code. I'm there as well.

You can also see us inworld, of course. New accounts can't be created, but you can get in without having one by hitting a "skip" button (on the bottom right I think). If you want to connect you can still download the latest client: https://www.highfidelity.com/download

Or you could use one of our currently experimental installers. We support Windows and Linux. In this case please come to our Discord.

Thanks!

**Pull request merged**
